# Generated by Django 5.2.6 on 2025-09-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_remove_shipment_destination_remove_shipment_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('On Hold', 'On Hold'), ('In Transit', 'In Transit'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('ORDER_PLACED', 'Order Placed'), ('LEFT_WAREHOUSE', 'Left Warehouse'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered')], default='ORDER_PLACED', max_length=20),
        ),
    ]
