# Generated by Django 4.2.16 on 2025-11-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_alter_shipment_status_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='package_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='package',
            old_name='quantity',
            new_name='PACKAGE_QUANTITY',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='tracking_number',
            new_name='TRACK_ID',
        ),
        migrations.RemoveField(
            model_name='package',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='package',
            name='description',
        ),
        migrations.RemoveField(
            model_name='package',
            name='image',
        ),
        migrations.RemoveField(
            model_name='package',
            name='name',
        ),
        migrations.RemoveField(
            model_name='package',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='amount_due',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='departure_datetime',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='expected_arrival_datetime',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='package_description',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='price',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='receiver_address',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='receiver_city',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='receiver_country',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='receiver_email',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='receiver_full_name',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shipper_address',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shipper_city',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shipper_country',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shipper_email',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shipper_full_name',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='transit_point',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='weight',
        ),
        migrations.AddField(
            model_name='package',
            name='PACKAGE_NAME',
            field=models.CharField(default='Package', max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='PACKAGE_WEIGHT',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='DESTINATION_ADDRESS',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='shipment',
            name='DISPATCH_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='DISPATCH_OFFICE',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='shipment',
            name='EXPECTED_DELIVERY_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='ORIGIN_ADDRESS',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='shipment',
            name='PICKUP_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='RECEIVER_CONTACT_ADDRESS',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='shipment',
            name='RECEIVER_CONTACT_NAME',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='RECEIVER_ORIGIN_CITY',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='RECEIVER_PHONE_NUMBER',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='SENDER_CONTACT_ADDRESS',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='shipment',
            name='SENDER_CONTACT_NAME',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='SENDER_COUNTRY',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='SENDER_ORIGIN_CITY',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='SENDER_PHONE_NUMBER',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='package',
            name='images',
            field=models.ManyToManyField(blank=True, to='tracking.packageimage'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='RECEIVER_COUNTRY',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='STATUS',
            field=models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('LEFT_WAREHOUSE', 'Left Warehouse'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered')], default='ORDER_PLACED', max_length=50),
        ),
    ]
